apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'email-smtp.us-east-1.amazonaws.com:587'
      smtp_from: 'vineet54@umd.edu'
      smtp_auth_username: 'AKIA2S2Y37YUNVDPUOUH'
      smtp_auth_password: 'BIQqPW6E3EG72iF15fw8yncWrjYrnFiCfIpZ9jrgIYfl'
    route:
      receiver: 'email'
    receivers:
    - name: 'email'
      email_configs:
      - to: 'vineet54@umd.edu'
        send_resolved: true